# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda


jobs:
  allow_failures:
    - arch: arm64

  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9-dev'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/apeye
        provider: pypi
        user: "DomDF"
        password:
          secure: CUAg7iAXVk9hpG5Y/79rVtrlnzIU7yN3NDbxDMrD49a/8hkEQFBJwHN4kLM6gXqMBe0zVH0Gv3ToQKx2hJZlLGNj3dF3bjlNd7W3YKoMo8JzJVWxUF41Icg9d/8rAep1dKw2wg8S/sC4857tkIK5pkzJdGk0mgP74ZHUeKDSAxc3N11h2HNWybBB5SWwZsgqxkaV/Vo65bKVxApPXutxEg3ODNtRBVAjb58a7HpRAF9WmkYzboXk0V6+dE0Hyv8bXgQrl4xPBxR9BRcOWjNnmjpj1lBi1yH6LJPggmYwqGMjM4fpEEgAoQhVrDQoDH9xwoR2R6mxhAJqadIRNZM0+s0hLE3s/MPr5oqK/r0+gSZnLrvcKJwQ/8hupG/3rMYMP2MNcw8EsXM8o7Jh36MWaqkwh1F5FjoBGVqlVOSFsPpN4QeA4NWUOXwBSkD84orgtBGkXzxj/rg8LaUFI+WDsPiq7F+qr+fHv8j3EjYsWQn1k2ePCnwNUn2WSSlWhT33aUa8KMVbbYhW8Fnyy/HpZ8gTk+wn0dQHpwyFSwnwWVgPGnRLF+liJv+ONsDxxoeYyYIBlLHL0NyyUY2pThZBkQNGqnceE5Obms6qm9vPm9iGKYRucZoUVB1XjkOFxEKczPkH7KA9RTiVMNb5MjTVbsm0EyBrM4ZDi7O2Bv0b5zM=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
